version: '3'
services:

  siat-db:
    image: "postgres:13.3"
    container_name: siat-db
    volumes:
        - siat-data:/var/lib/postgresql/data
    ports:
        - 5432
    environment:
        POSTGRES_DB: 'siat-tec'
        POSTGRES_USER: 'siat'
        POSTGRES_PASSWORD: 'testpass'

  siat-api:
    image: "vini24/siat-tec:api"
    container_name: siat-api
    environment:
        - DB_HOST=siat-db
    ports:
        - 8000:8000
    links:
        - siat-db

  siat-client:
    image: "vini24/siat-tec:client"
    container_name: siat-client
    restart: always
    volumes:
        - ./webserver/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./webserver/nginx/siat.codes.conf:/etc/nginx/sites-enabled/siat.codes.conf
        - ./webserver/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./webserver/certbot/conf:/etc/letsencrypt
        - ./webserver/certbot/www:/var/www/certbot
    ports:
        - 80:80
        - 443:443
    restart: unless-stopped
    links:
        - siat-api
    command: /bin/sh -c "while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g 'daemon off;'"

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
        - ./webserver/certbot/conf:/etc/letsencrypt
        - ./webserver/certbot/www:/var/www/certbot
    restart: unless-stopped
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;" # ðŸ’¡
    links:
        - siat-client
    depends_on:
        - siat-client

volumes:
    siat-data:
